name: Start Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  version-and-changelog:
    name: Version and Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install AutoVer
        run: dotnet tool install -g AutoVer
      - name: Setup Git User
        run: |
          git config --global user.email "github-user@email.com"
          git config --global user.name "GitHub User"
      - name: Increment Version
        run: autover version
      - name: Update Chagelog
        run: autover changelog
      - name: Push Changes
        run: git push && git push origin --tags
  nuget-release:
    needs: version-and-changelog
    name: Package Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Solution
        run: dotnet build
      - name: Create NuGet Package
        run: dotnet pack
      - name: Push to GitHub Registry
        run: |
          dotnet nuget add source --username philasmar --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/philasmar/index.json"
          dotnet nuget push src/AutoVer/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
      - name: Push to NuGet
        run: dotnet nuget push src/AutoVer/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}  --source "https://api.nuget.org/v3/index.json"